### ISSUE TITLE
Able to trigger a leader election panic, use of closed channel

### ISSUE THREAD

**Issue by smarterclayton** [openshift/cluster-version-operator#142]
TEST_INTEGRATION=1 go test ./pkg/start/ -tags integration -count=4

```
E0325 22:45:48.713617   10713 sync_worker.go:276] unable to synchronize image (waiting 625ms): Could not update configmap "e2e-cvo-ff4l/config2" (2 of 2): the object is invalid, possibly due to local cluster configuration
E0325 22:45:48.922205   10713 leaderelection.go:256] error initially creating leader election record: namespaces "e2e-cvo-mlm6zv" not found
E0325 22:45:54.301108   10713 event.go:259] Could not construct reference to: '&v1.ConfigMap{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Data:map[string]string(nil), BinaryData:map[string][]uint8(nil)}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'LeaderElection' 'claytonc-mbp.local_4bb2f5bb-5f1d-4543-90dd-75de07986a26 stopped leading'
panic: close of closed channel

goroutine 63 [running]:
github.com/openshift/cluster-version-operator/pkg/start.(*Options).run.func3()
	/Users/clayton/projects/origin/src/github.com/openshift/cluster-version-operator/pkg/start/start.go:190 +0x74
github.com/openshift/cluster-version-operator/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run.func1(0xc0006e4240)
	/Users/clayton/projects/origin/src/github.com/openshift/cluster-version-operator/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:148 +0x40
github.com/openshift/cluster-version-operator/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0xc0006e4240, 0x216d1e0, 0xc000184600)
	/Users/clayton/projects/origin/src/github.com/openshift/cluster-version-operator/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:157 +0x112
github.com/openshift/cluster-version-operator/vendor/k8s.io/client-go/tools/leaderelection.RunOrDie(0x216d220, 0xc0000da010, 0x2174320, 0xc0001e5d40, 0x14f46b0400, 0xa7a358200, 0x6fc23ac00, 0xc0003b03f0, 0xc0000d13b0, 0x0)
	/Users/clayton/projects/origin/src/github.com/openshift/cluster-version-operator/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:166 +0x87
created by github.com/openshift/cluster-version-operator/pkg/start.(*Options).run
	/Users/clayton/projects/origin/src/github.com/openshift/cluster-version-operator/pkg/start/start.go:157 +0x1ef
FAIL	github.com/openshift/cluster-version-operator/pkg/start	75.329s
```

**Comment by smarterclayton** [comment]
This can happen if the lease is stolen while the code is trying to release the lease.

**Comment by asalkeld** [comment]
close?
